### ISSUE TITLE
Issues with Relationships Feature

### ISSUE THREAD

**Issue by john19950730** [CS2103AUG2017-F10-B1/main#116]
This acceptance testing is done on version 1.3, since that's the newest release I see. I think there are several issues with the `Relationship` feature as follows:

None of the relationships that has been added are saved when the application is closed.

The graphical representation of the relationships can be very distracting if it is updated for **every** command executed.

There are no way to remove relationships between the persons in the list, hopefully that gets listed in upcoming features at least.

`addRelationship` command is not listed by the autocomplete feature, and is not the only command to be left out.

**Comment by LuLechuan** [comment]
I am also testing on their product. However, the latest release is v1.4 and the relationships are saved. Therefore no problem with that issue.

**Comment by john19950730** [comment]
Nice.
