### ISSUE TITLE
[Acceptance Testing] addRelationship command

### ISSUE THREAD

**Issue by seankwekjk** [CS2103AUG2017-F10-B1/main#124]
Personally I feel that the command usage provided is very confusing. Please include an example to provide clarity in how it should be used

**Comment by Xenonym** [comment]
Hi @seankwekjk could you perhaps clarify confusing how?

**Comment by seankwekjk** [comment]
@Xenonym Below is your command usage string as prompted by your addressbook.

How to use:
addRelationship FROM_INDEX, TO_INDEX (must be positive integers), DIRECTION (either "directed" or "undirected"), (Optional) ce/CONFIDENCE_ESTIMATE, (Optional) n/NAME. [INDEXOFFROMPERSON] [INDEXOFTOPERSON] [DIRECTION] ce/[CONFIDENCE_ESTIMATE} n/[NAME]

There are multiple arguments that appear to be repeated after the period, with no explanation provided regarding them, and the use of text within brackets adds to the length of the string of text.

The instructions provided in your User Guide are not as confusing, but it appears to be inconsistent as there is nothing mentioned about confidence estimate or name in the instructions there.

**Comment by Xenonym** [comment]
Thank you @seankwekjk for the response! We will look into how best to clarify this or simplify the command altogether.

Pinging @joanneong (short command description) and @wenmogu (feature implementation).

**Comment by Xenonym** [comment]
Fixed.
