### ISSUE TITLE
(Testing) Confidence Estimates in addRelationship

### ISSUE THREAD

**Issue by derrickchua** [CS2103AUG2017-F10-B1/main#125]
Confidence Estimates currently have no restriction, and can be any integer value.

**Comment by Xenonym** [comment]
@wenmogu is this a bug or is this intended?

**Comment by wenmogu** [comment]
Hello Derrick! thanks for your comment. I purposely left the confidence estimate to be restriction free as the users can define their own usage of this feature using the number ranges they like (e.g. some like integers but some like decimals and even some like negative numbers). However after our group discussion we decide to use values between 0 - 100 for easier implementation of other features. Thank you again for the feedback.
