### ISSUE TITLE
Default window size does not make sense for graph display

### ISSUE THREAD

**Issue by Xenonym** [CS2103AUG2017-F10-B1/main#132]
Currently, the app defaults to a 500 x 500 window size on first startup when `preferences.json` does not exist. This is not a sensible default as it would make more sense for the default size to be more rectangular to hold a graph display eg. 1500 x 500. 

Let's put in a more sensible default window size so its obvious on first start that there is a graph display.

This is what the window currently looks like on first start:

![image](https://user-images.githubusercontent.com/1782590/32617167-37346300-c5af-11e7-856a-7c4c53fd0baf.png)

**Comment by joanneong** [comment]
Closed by #139
