### ISSUE TITLE
Reassign priorities for user stories

### ISSUE THREAD

**Issue by joanneong** [CS2103AUG2017-F10-B1/main#52]
Based on the feedback that we received for our first PR, we have to reassign priorities for our user stories such that our must-haves will form a Minimum Viable Product (MVP). This is because the current assignment includes 'unnecessary' user stories under the 'must-have' priorities. 

Feel free to take the initiative to self-assign this issue.

**Comment by Xenonym** [comment]
Fulfilled by #53.
