### ISSUE TITLE
Update About Us page with roles, responsibilities, and profile picture

### ISSUE THREAD

**Issue by Xenonym** [CS2103AUG2017-F10-B1/main#54]
Hi everyone, please update [AboutUs.adoc](https://github.com/CS2103AUG2017-F10-B1/main/blob/master/docs/AboutUs.adoc) with 

- your roles and responsibilities
- a profile picture at `doc/images/githbub_id_in_lower_case.png`, edit the page to point to the picture as necessary.

and reference this issue when creating your pull request.

Please also make sure to arrange yourself in **alphabetical** order, for ease of merging! That is,

1. Joanne Ong
2. Tan Yikai
3. Tan Zhen Yong
4. Wen Xin

[More info on module page.](https://nus-cs2103.github.io/website/admin/index.html#admin-project-v11)

**Comment by joanneong** [comment]
I suppose `jpg` format is fine as well?

**Comment by Xenonym** [comment]
Presumably, the sample images are all in `.jpg` format.

**Comment by Xenonym** [comment]
Probably? The sample images are all in `.jpg` format.

**Comment by Xenonym** [comment]
Fulfilled by #57.
