### ISSUE TITLE
Update README.md with new UI mockup and description

### ISSUE THREAD

**Issue by joanneong** [CS2103AUG2017-F10-B1/main#58]
Update `README.md` to match the team project. In particular, add a UI mockup of the team's intended final product.

Note that the image of the UI should be `docs/images/Ui.png`, and that we must acknowledge the original source of the code i.e. AddressBook-Level4 project created by SE-EDU initiative at https://github.com/se-edu/. However, the Learning Outcomes link and related pages can be removed from the page.

**Comment by Xenonym** [comment]
Fulfilled by #59.
